Repository mediunn/Livith-Web, pull requests merged in 2025-09, with the labels that each got.

#143 [Fix/#141] 3차 스프린트 1차 QA
  src/features/interest/ui/SelectableInfiniteConcertList.tsx
  src/features/search/model/useSearchResult.ts
  src/features/setlist/ui/InterestConcertSetlist.tsx
  src/pages/SetInterestConcertPage.tsx
  src/widgets/ChangeConcertConfirmModal.tsx
  src/widgets/DeleteConfirmModal.tsx
Labels: 🐛 Bug, 🎨 Style

#145 [Feat/#144] 셋리스트 상세 화면 UI 구현
  src/entities/concert/ui/SetlistTabPanel.tsx
  src/entities/setlist/ui/SetListCard.tsx
  src/entities/setlist/ui/SetlistSongList.tsx
  src/features/setlist/ui/BriefSetlistSongList.tsx
  src/features/setlist/ui/InterestConcertSetlist.tsx
  src/pages/SetlistDetailPage.tsx
  src/widgets/ChangeConcertConfirmModal.tsx
  src/widgets/DeleteConfirmModal.tsx
Labels: ✨ Feat, 🎨 Style, 🗒️ 셋리스트 페이지

#147 [Feat/#142] 3차 스프린트 1차 QA
  src/entities/concert/ui/ConcertInfoTab.tsx
  src/entities/concert/ui/FanCultureSwiper.tsx
  src/entities/concert/ui/RequiredInfo.tsx
  src/features/concert/ui/ConcertSetting.tsx
  src/features/concert/ui/ConcertSettingEmpty.tsx
  src/shared/ui/DetailInfo.tsx
Labels: 🐛 Bug, 🎨 Style, 🏠 홈 페이지, 🎤 콘서트 페이지

#151 [Feat/#150] 앰플리튜드 이벤트 태깅
  src/app/amplitude.d.ts
  src/entities/concert/ui/ArtistInfo.tsx
  src/entities/concert/ui/ConcertInfoTab.tsx
  src/entities/concert/ui/FanCultureInfo.tsx
  src/entities/concert/ui/RequiredInfo.tsx
  src/entities/concert/ui/ScheduleInfo.tsx
  src/entities/concert/ui/SectionConcertSlide.tsx
  src/entities/concert/ui/SetlistTabPanel.tsx
  src/entities/setlist/ui/SetlistSongList.tsx
  src/features/concert/ui/ConcertSetting.tsx
  src/features/concert/ui/ConcertSettingEmpty.tsx
  src/features/interest/ui/EditInterestConcertBottomSheet.tsx
  src/features/lyric/ui/LyricTypeButton.tsx
  src/features/lyric/ui/MusicTitleBar.tsx
  src/features/setlist/ui/BriefSetlistSongList.tsx
  src/pages/CategoryPage.tsx
  src/shared/ui/DetailInfo.tsx
  src/shared/ui/TabBar.tsx
  src/widgets/ChangeConcertConfirmModal.tsx
  src/widgets/DeleteConfirmModal.tsx
  src/widgets/PopularConcert.tsx
  src/widgets/SearchConcertList.tsx
Labels: ✨ Feat, 🗒️ 셋리스트 페이지, 🎤 콘서트 페이지, 🆎 가사 페이지, 👀 탐색 페이지

#156 [Fix/#155] 바텀시트 UI 수정
  src/app/index.css
  src/pages/LyricPage.tsx
Labels: 🐛 Bug, 🎨 Style

#157 [Feat/#146] 필터를 적용한 검색 기능 구현
  src/entities/concert/constants/filterMaps.ts
  src/entities/concert/types/index.ts
  src/features/search/api/getSearchResult.ts
  src/features/search/model/useFilterSearch.ts
  src/features/search/ui/FilterBottomSheet.tsx
  src/features/search/ui/FilterChips.tsx
  src/features/search/ui/FilterSearch.tsx
  src/features/search/ui/InputSearchBar.tsx
  src/features/search/ui/SearchResult.tsx
  src/features/search/ui/SortMenu.tsx
  src/pages/SearchPage.tsx
  src/shared/assets/CalendarIcon.tsx
  src/shared/assets/CloseBlackIcon.svg
  src/shared/assets/FilterDownIcon.svg
  src/shared/assets/MicIcon.svg
  src/shared/assets/MicIcon.tsx
  src/shared/assets/SortDown.svg
  src/shared/assets/SortUp.svg
  src/widgets/InfiniteConcertList.tsx
Labels: ✨ Feat, 🔗 API, 🎨 Style, 👀 탐색 페이지

#163 [Fix/#162] 3차 스프린트 2차 QA
  src/entities/concert/constants/filterOrders.ts
  src/entities/setlist/ui/SetlistDetail.tsx
  src/features/concert/utils/sortFilter.ts
  src/features/interest/ui/EditInterestConcertBottomSheet.tsx
  src/features/search/ui/FilterBottomSheet.tsx
  src/features/search/ui/FilterChips.tsx
  src/pages/HomePage.tsx
  src/pages/SetInterestConcertPage.tsx
  src/widgets/CompleteSetConcert.tsx
  src/widgets/DeleteConfirmModal.tsx
Labels: 🐛 Bug

#166 [Feat/#161] 탐색 페이지 검색창 UI
  src/pages/CategoryPage.tsx
Labels: ✨ Feat, 🎨 Style

#168 [Feat/#164] 팝업 인터랙션
  src/app/RootLayout.tsx
  src/features/concert/ui/ConcertSetting.tsx
  src/features/concert/ui/ConcertSettingEmpty.tsx
  src/features/lyric/ui/LyricModal.tsx
  src/pages/ConcertInsidePage.tsx
  src/pages/ConcertListPage.tsx
  src/pages/HomePage.tsx
  src/pages/LyricPage.tsx
  src/pages/MdPage.tsx
  src/pages/MyPage.tsx
  src/pages/SetInterestConcertPage.tsx
  src/pages/SetlistCollectionPage.tsx
  src/pages/SetlistDetailPage.tsx
  src/shared/hooks/useTabDirection.ts
  src/shared/recoil/atom/tabDirectionState.ts
  src/shared/ui/TabBar.tsx
  src/widgets/ChangeConcertConfirmModal.tsx
  src/widgets/DeleteConfirmModal.tsx
Labels: ✨ Feat, 🎨 Style

#169 [Feat/#165] 3차 스프린트 2차 QA
  src/entities/concert/ui/ArtistTabPanel.tsx
  src/features/my/ui/Info.tsx
  src/pages/LyricPage.tsx
Labels: 🐛 Bug, 🎨 Style

#171 [Fix/#170] 관심 콘서트 설정 엠티뷰
  src/entities/concert/model/useConcertInsideInfo.ts
  src/entities/concert/model/useSchedule.ts
  src/features/concert/model/useBanner.ts
  src/features/concert/model/useHomeConcertList.ts
  src/features/concert/model/useSearchConcertList.ts
  src/pages/HomePage.tsx
  src/widgets/MainImageCarousel.tsx
  src/widgets/PopularConcert.tsx
  src/widgets/SearchConcertList.tsx
Labels: 🐛 Bug, 🏠 홈 페이지

#172 [Feat/#167] 인터랙션 및 스켈레톤 추가
  src/features/concert/ui/ConcertCardListSkeleton.tsx
  src/features/concert/ui/ConcertCardSkeleton.tsx
  src/features/concert/ui/ConcertScheduleSkeleton.tsx
  src/features/interest/ui/SelectableConcertList.tsx
  src/features/interest/ui/SelectableInfiniteConcertList.tsx
  src/features/interest/ui/SetInterestConcertButton.tsx
  src/features/search/ui/FilterBottomSheet.tsx
  src/features/search/ui/FilterChips.tsx
  src/features/search/ui/FilterSearch.tsx
  src/features/search/ui/SearchResult.tsx
  src/pages/HomePage.tsx
  src/widgets/PopularConcert.tsx
  src/widgets/SearchConcertList.tsx
  tailwind.config.js
Labels: 🎨 Style

#180 [Feat/#179] 구글 애드센스
  index.html
Labels: ✨ Feat

#182 [Feat/#181] 네이버 웹마스터
  index.html
  public/robots.txt
  public/sitemap.xml
Labels: ✨ Feat
