Repository mediunn/Livith-Web, pull requests merged in 2025-08, with the labels that each got.

#98 [Feat/#96] 콘서트 목록 조회 API
  src/features/concert/api/getConcertList.ts
  src/pages/ConcertListPage.tsx
  src/widgets/InfiniteConcertList.tsx
  src/widgets/NewConcert.tsx
Labels: ✨ Feat, 🔗 API, 🎨 Style, 🎤 콘서트 페이지

#100 [Feat/#99] 홈 화면 API
  src/features/concert/ui/ConcertSetting.tsx
  src/features/concert/ui/ConcertSettingEmpty.tsx
  src/features/concert/ui/EmptyConcertSchedulePanel.tsx
  src/features/concert/utils/formatScheduleDate.ts
  src/pages/HomePage.tsx
Labels: ✨ Feat, 🔗 API, 🎨 Style, 🏠 홈 페이지

#103 [Fix/#102] 가사 페이지 이동
  src/entities/concert/ui/ConcertInfoTab.tsx
  src/entities/concert/ui/SetlistTabPanel.tsx
  src/entities/setlist/ui/SetListCard.tsx
  src/entities/setlist/ui/SetlistCollection.tsx
  src/entities/setlist/ui/SetlistSongList.tsx
  src/pages/ConcertInsidePage.tsx
  src/pages/LyricPage.tsx
  src/widgets/ExpectationSetList.tsx
  src/widgets/OngoingSetList.tsx
  src/widgets/PastSetList.tsx
Labels: 🐛 Bug, 🎤 콘서트 페이지, 🆎 가사 페이지

#105 [Feat/#101] 관심있는 콘서트 수정/삭제 UI 및 기능 구현
  package-lock.json
  package.json
  src/entities/setlist/ui/SetlistDetail.tsx
  src/entities/setlist/ui/SetlistSongItem.tsx
  src/features/concert/ui/ConcertSetting.tsx
  src/features/interest/ui/EditInterestConcertBottomSheet.tsx
  src/shared/assets/EditIcon.svg
  src/shared/assets/TrashCanIcon.svg
  src/shared/assets/WarningIcon.svg
  src/widgets/DeleteConfirmModal.tsx
  tailwind.config.js
Labels: ✨ Feat, 🔗 API, 🎨 Style

#107 [Feat/#106 2차 스프린트 1차 QA
  package-lock.json
  src/app/App.tsx
  src/features/concert/model/useConcertDetail.ts
  src/features/concert/ui/ConcertSettingEmpty.tsx
  src/features/interest/ui/EditInterestConcertBottomSheet.tsx
  src/features/interest/ui/SetInterestConcertButton.tsx
  src/shared/assets/CompleteEffect.svg
  src/shared/assets/Subtract.svg
  src/widgets/CompleteSetConcert.tsx
  tailwind.config.js
Labels: 🐛 Bug, 🎨 Style, 🎤 콘서트 페이지

#110 [Fix/#109] 2차 스프린트 2차 QA
  src/entities/concert/ui/ArtistInfo.tsx
  src/entities/concert/ui/ConcertCard.tsx
  src/entities/concert/ui/ConcertCultureCarouselSlide.tsx
  src/entities/concert/ui/ConcertInfoTab.tsx
  src/entities/concert/ui/ConcertSlideCard.tsx
  src/entities/concert/ui/ConcertTabPanel.tsx
  src/entities/concert/ui/EmptyConcertInfoTabPanel.tsx
  src/entities/concert/ui/FanCultureInfo.tsx
  src/entities/concert/ui/FanCultureSwiper.tsx
  src/entities/concert/ui/MdCard.tsx
  src/entities/concert/ui/MdInfo.tsx
  src/entities/concert/ui/MdSlide.tsx
  src/entities/concert/ui/MdSlideCard.tsx
  src/entities/concert/ui/RequiredInfo.tsx
  src/entities/concert/ui/ScheduleInfo.tsx
  src/entities/concert/ui/SetlistTabPanel.tsx
  src/entities/lyric/ui/Lyric.tsx
  src/entities/lyric/ui/LyricFanchant.tsx
  src/entities/setlist/ui/SetListCard.tsx
  src/entities/setlist/ui/SetlistDetail.tsx
  src/entities/setlist/ui/SetlistSongItem.tsx
  src/entities/setlist/ui/SetlistSongList.tsx
  src/features/concert/ui/ConcertSetting.tsx
  src/features/concert/ui/ConcertSettingEmpty.tsx
  src/features/concert/ui/EmptyConcertCulture.tsx
  src/features/concert/ui/EmptyConcertSchedulePanel.tsx
  src/features/concert/ui/EmptyConcertSlide.tsx
  src/features/interest/ui/EditInterestConcertBottomSheet.tsx
  src/features/interest/ui/SelectableInfiniteConcertList.tsx
  src/features/interest/ui/SetInterestConcertButton.tsx
  src/features/lyric/ui/LyricTypeButton.tsx
  src/features/lyric/ui/MusicTitleBar.tsx
  src/features/my/ui/Info.tsx
  src/features/my/ui/ReportConcert.tsx
  src/features/search/ui/EmptySearchResult.tsx
  src/features/search/ui/InputSearchBar.tsx
  src/features/search/ui/RecentSearch.tsx
  src/features/search/ui/RecentSearchItem.tsx
  src/features/search/ui/RecommendSearchItem.tsx
  src/features/search/ui/SearchResultCount.tsx
  src/features/setlist/ui/BriefSetlistSongList.tsx
  src/features/setlist/ui/EmptySetList.tsx
  src/features/setlist/ui/EmptySongList.tsx
  src/features/setlist/ui/InterestConcertSetlist.tsx
  src/pages/LyricPage.tsx
  src/pages/MdPage.tsx
  src/shared/ui/DetailInfo.tsx
  src/shared/ui/ListHeader.tsx
  src/shared/ui/TabBar.tsx
  src/widgets/AllConcert.tsx
  src/widgets/CompleteSetConcert.tsx
  src/widgets/ConcertInfoCarouselSlide.tsx
  src/widgets/DeleteConfirmModal.tsx
  src/widgets/InfiniteConcertList.tsx
  src/widgets/InterestConcertSetlistDetail.tsx
  src/widgets/MainImageCarouselSlide.tsx
  src/widgets/MdList.tsx
  src/widgets/NewConcert.tsx
  src/widgets/UpcomingConcert.tsx
  tailwind.config.js
Labels: 🎨 Style, 🏠 홈 페이지, 🔍 검색 페이지, 🎤 콘서트 페이지

#112 [Fix/#111] 2차 스프린트 2차 QA
  src/entities/concert/ui/ConcertCard.tsx
  src/entities/concert/ui/SetlistTabPanel.tsx
  src/entities/setlist/ui/SetlistSongItem.tsx
  src/features/concert/api/getBanner.ts
  src/features/concert/ui/ConcertSetting.tsx
  src/features/interest/ui/SetInterestConcertButton.tsx
  src/features/my/ui/ReportConcert.tsx
  src/features/search/ui/InputSearchBar.tsx
  src/features/setlist/ui/BriefSetlistSongList.tsx
  src/features/setlist/ui/EmptySetList.tsx
  src/features/setlist/ui/EmptySongList.tsx
  src/features/setlist/ui/InterestConcertSetlist.tsx
  src/shared/ui/DetailInfo.tsx
  src/widgets/CompleteSetConcert.tsx
  src/widgets/InterestConcertSetlistDetail.tsx
  src/widgets/MainImageCarousel.tsx
  src/widgets/MainImageCarouselSlide.tsx
  tailwind.config.js
Labels: 🐛 Bug, 🎨 Style

#116 [Fix/#115] 정보 엠티뷰
  src/entities/concert/ui/ArtistInfo.tsx
  src/entities/concert/ui/ConcertSlide.tsx
  src/entities/concert/ui/ConcertSlideCard.tsx
  src/pages/ConcertInsidePage.tsx
  src/shared/assets/EmptyArtistImageIcon.svg
  src/shared/assets/EmptyConcertInfoIcon.svg
  src/widgets/ConcertInfoCarouselSlide.tsx
Labels: 🐛 Bug, 🎨 Style, 🎤 콘서트 페이지

#124 [Feat/#123] 앰플리튜드 세팅하기
  index.html
Labels: ✨ Feat

#127 [Feat/#126] 홈 화면 UI 구현
  package-lock.json
  package.json
  src/app/App.tsx
  src/entities/setlist/ui/SetlistSongItem.tsx
  src/features/concert/ui/ConcertSetting.tsx
  src/features/setlist/ui/BriefSetlistSongList.tsx
  src/features/setlist/ui/InterestConcertSetlist.tsx
  src/shared/assets/DeleteConcertToastIconMotion.json
  src/shared/assets/InterestConcertToastIconMotion.json
  src/widgets/DeleteConfirmModal.tsx
  src/widgets/Toast.tsx
  tailwind.config.js
Labels: ✨ Feat, 🎨 Style, 🏠 홈 페이지

#134 [Feat/#131] 탐색 화면
  src/features/concert/api/getBanner.ts
  src/features/concert/api/getSearchConcertList.ts
  src/pages/CategoryPage.tsx
  src/widgets/MainImageCarousel.tsx
  src/widgets/SearchConcertList.tsx
Labels: ✨ Feat, 🔗 API, 🎨 Style, 👀 탐색 페이지

#140 [Fix/#139] useConcertList 파일 빌드 오류 해결
  src/features/concert/model/useConcertList.ts
  src/features/search/model/useSearchResult.ts
Labels: 🐛 Bug
